version: '3'

services:
  web:
    image: "node:14"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    command: "npm start"




